### ISSUE TITLE
0B/s to Download Failure? My Download Speed is 100+MBPS

### ISSUE THREAD

**Issue by iRuthl3ss** [blastrock/pkgj#141] opened 2018-07-11 18:17 UTC
Version of firmware: 3.65
Version of PKGj: 0.28

Hello, I just updated to the enzo 3.65 and downloaded the newest PKGJ
Everytime I download something it will initially start off at a okay download speed, then suddenly stop at 0B/s and show a download failure with a Http error 0x80431068?

It worked perfect on my 3.60? I even downgraded PKGj versions to see if that would fix it but nothing is working....

**Comment by blastrock** [comment] 2018-07-11 18:24
That's the error `SCE_HTTP_ERROR_TIMEOUT | 0x80431068 | NW-5603-4 | Could not connect to the server in time.`. You somehow lost connection, I think it's a problem with your wifi.

**Comment by iRuthl3ss** [comment] 2018-07-11 18:46
I can assure you it's not my connection. I just stress tested it on my mobile device and computer through the same 2.4Ghz connection and it is working consistently fine. As example is I'll download undertale, hit about 2mb/s then it will drop to 0, then back up, then it will completely stop at 0 and give me the error. I reset the router and everything, plus it worked on my 3.60 FW

**Comment by blastrock** [comment] 2018-07-11 19:04
Try taking the link out of the TSV file and downloading it through the vita's browser, just to see if it works. It seems lots of people are having these issues with pkgj, but I just never hit them...

**Comment by blastrock** [comment] 2018-07-11 19:04
btw this is a duplicate of #104, closing this one

**Closed by blastrock** 2018-07-11 19:04 UTC

**Comment by iRuthl3ss** [comment] 2018-07-11 19:12
I did a hard reset on my router. Works fine, thank you and sorry!
