### ISSUE TITLE
Games download, but do not install.

### ISSUE THREAD

**Issue by YoItsTrev** [blastrock/pkgj#30] opened 2018-03-31 20:27 UTC
Just updated my Vita to 3.65 Enso. Updated my SD2Vita, and NoNpDRM. Installed PGKj 0.9. Every time I try to download a game, it gets to 100%, and then goes idle. It does not install the game. I know for a fact that NoDpDRM is working, because I used NPS Browser to download games, and manually transfer them over, and they work. I tried to download Terraria and Steamworld Dig for testing, cause they are small... They downloaded to 100%, then went to idle. They did not install. In ux0:pkgi there are 2 directories:

UP4040-PCSE00317_00-TERRARIA00000001
UP4473-PCSE00430_00-STEAMWORLDDIG000

With what seems to be full file structures. Any idea why the games are not being installed?

**Comment by edale2** [comment] 2018-04-01 03:24
Try deleting everything in the ux0:pkgi/ folder except for the config file, then downloading the games again. This has fixed every problem I've had that's similar to this.

**Comment by YoItsTrev** [comment] 2018-04-01 04:02
Yes, I tried that. Still would not install.

**Comment by edale2** [comment] 2018-04-01 05:24
If downloading via WiFi, they might be getting corrupted, other than that, I got nothing.

**Comment by YoItsTrev** [comment] 2018-04-01 05:37
I didn't have these issues with 0.8 prior to upgrading to 3.65.

**Comment by alpsark** [comment] 2018-04-01 19:11
Try rebooting after installing , I had the same problem and restarting solved it.

**Comment by YoItsTrev** [comment] 2018-04-02 00:31
I restart after everything I do on the Vita, no matter how minor.

**Comment by YoItsTrev** [comment] 2018-04-02 01:15
Uninstalled and installed 0.10. Same thing. Going to try going back to .8

**Comment by YoItsTrev** [comment] 2018-04-02 01:19
0.08 did the same thing.... *sigh*

**Comment by blastrock** [comment] 2018-04-02 08:26
I will work on error reporting on the next version to help with these kind of problems.

**Comment by RealRaptoReX** [comment] 2018-04-04 23:43
On the latest version, mine doesn't install vita games, but downloads them. ps1 games work just fine. Can we get any help?

**Comment by edale2** [comment] 2018-04-05 02:12
@RealRaptoReX You need more info than that for a bug report to get any useful help.

Vita Firmware version
PKGj version
Title ID of the game(s) you tried downloading/installing (alternately the name & region of game, but the  Title ID is better)

That's the bare basics you need to include.

Without that info, the most I (or more importantly the dev) can suggest is using VitaShell or an FTP program (I use FileZilla) to delete everything but config.txt from the ux0:pkgi/ directory and retry downloading the game(s).

I just tried downloading a small Vita game (Aabs Animals, EU, PCSB00384, only 52.79 MB), and it downloaded and installed fine while using PKGj v0.11.

**Comment by RealRaptoReX** [comment] 2018-04-06 04:06
Oh my bad...

Vita Firmware: 3.60 Henkaku
PKGj Verion: 0.11 (latest)
Title IDs i can't see at the moment since i don't have the Vita with me but you don't need them honestly since it's not like specific games don't work, all of them don't work. I downloaded Metal Gear Solid HD collection, Retro City Rampage DX and another one i can't remember, all PAL region. I also downloaded Apps like YouTube and Live something, won't work either. All of these are being downloaded, they're in the pkgi folder, but won't install.

Yeah i could do that, but the Vita would've downloaded and installed it correctly the first time since i created the folder brand new, i didn't hat pkgi before, so it makes no difference.

I added nonpdrm.skprx to both ux0 and ur0 and added them to both configs under KERNEL, and it still didn't work. I don't get why.

**Comment by edale2** [comment] 2018-04-06 08:17
>I added nonpdrm.skprx to both ux0 and ur0 and added them to both configs under KERNEL, and it still didn't work. I don't get why.

Yea...Do what ShroomKing said, and delete the ux0:tai/ folder entirely, and use the config in ur0:tai/ Much easier to keep things straight when you only have one set of config files/plugins to work with, not to mention I have no clue what would happen if you got 2 copies of the same plugin running, but it probably wouldn't work as intended.

I'd use the NPS browser to grab a small game (there are a number of Vita games at around 50 MB), then use that to check if your NPS browser is working correctly (transfer the game into ux0:app/ and use VitaShell to refresh the livearea), if the game shows up and works, then you know the nonpdrm plugin is working (you can then delete the game if desired).

**Comment by RealRaptoReX** [comment] 2018-04-06 14:09
But i did that only after it didn't work on one config. If i delete my entire ux0 folder, all my plugins will be gone.

The nps browser i never used before, i will give that a shot.

**Comment by RealRaptoReX** [comment] 2018-04-06 18:04
So I moved all my plugins and the config from ux0/tai to ur:0/tai. I deleted everything from the pkgi folder and tried again, this time with the game LUFTRAUSERS (eur version), made sure the Vita doesn't turn off and it still doesn't work. Downloads and goes idle like before. Would you mind looking up my config.txt? I think something is wrong in there. I want all my plugins to work. Here is a list of my plugins:

-gamesd.skprx
-henkaku.skprx
-henkaku.suprx
-henkaku_config.bin
-noavls.skprx
-nonpdrm.skprx
-renpdrm.skprx
-restore.suprx
-taihen.skprx

And i'll attach my config file too. ignore that it is called config ux0.

[config ux0.txt](https://github.com/blastrock/pkgj/files/1885120/config.ux0.txt)

**Comment by edale2** [comment] 2018-04-06 19:45
https://pastebin.com/ydcxLzcX

That's my config.txt

**Comment by RealRaptoReX** [comment] 2018-04-06 20:25
No still nothing, even after i replaced my config with yours, pkgj goes idle, no installation. This is so frustrating.

**Comment by edale2** [comment] 2018-04-06 23:54
grab a small game off NPS browser to test if nonpdrm is working.

**Comment by RealRaptoReX** [comment] 2018-04-07 00:44
Okay i installed NPS Browsers latest version, downloaded Retro City Rampage DX because it is a small game and put it into ux0/app. It doesn't show up on the live area so nonpdrm is not working i think.

**Comment by edale2** [comment] 2018-04-07 03:13
Did you use vitashell to refresh the livearea after copying the game over?

**Comment by RealRaptoReX** [comment] 2018-04-07 03:32
Okay i did that now and it still didn't work. After that i added the line to uma0 and now it works, nps browser and pkgj. Should i add my other plugins to uma0 too? Restore.soprx and so on didn't work before, maybe they'll work when i put them in uma0?

**Comment by edale2** [comment] 2018-04-07 04:29
Looks like some sd2vita drivers set the vita's memory card as uma0 rather than leaving it unbound (the 3.65 one I have leaves it unbound IIRC, not sure because I don't actually own a memory card, lol), the tai folder in uma0 is probably from your henkaku install before you installed the sd2vita adapter.

**Comment by edale2** [comment] 2018-04-07 04:32
Oh, and you went all the taiHEN and plugin stuff running off ur0 rather than any other directory when using an sd2vita because that way it'll work even if your sd2vita adapter isn't in the system (or stops working, breaks, shifts enough to break contact, ect.).

**Comment by blastrock** [comment] 2018-04-07 06:45
Please retry with the last version, it should show you an error.

**Comment by RealRaptoReX** [comment] 2018-04-07 14:00
I don't know what uma0 is. Isn't that the vita memory card (the expensive ones)? I have a slim model and i still have a memory card in there in addition to sd2vita.
Should i move all my stuff to ur0 from uma0 and will it still work after that? I have the fear that it won't work after i moved everything

**Comment by edale2** [comment] 2018-04-07 15:57
You should just move your plugins to ur0:, and not have a tai folder in ux0: or uma0:. No need to move everything else out of uma0:.

**Comment by RealRaptoReX** [comment] 2018-04-07 16:16
Okay i did and now pkgj and rps browser is working like a charm. I have one question though. Where are the games stored that are being downloaded with pkgj? There are not in the pkgi folder anymore, are they in ux0:app?

**Comment by edale2** [comment] 2018-04-07 19:44
Yep, pkgj downloads the files to ux0:pkgi/ then installs them to ux0:app/ (or ux0:pspemu/ for psx games)

**Comment by RealRaptoReX** [comment] 2018-04-07 19:58
Okay thank you, all my problems are solved now! If only renpdrm.skprx and restore.suprx would work, everything would be perfect!

**Comment by edale2** [comment] 2018-04-07 21:10
Only thing I can find for renpdrm is renpdrm.skprx needs to be **before** nonpdrm.skprx in the config file.

That and a LOT of posts from people who can't get it working.

**Comment by RealRaptoReX** [comment] 2018-04-07 22:42
Yeah doesn't work for everyone.

I will look around for that. Tha ks for the help!

**Comment by RealRaptoReX** [comment] 2018-04-08 01:56
That sounds good, but if pkgj works i think i don't need the psn really. I only had a few games on there, so pkgj is doing a damn good job in replacing these.

**Comment by blastrock** [comment] 2018-04-28 16:06
Closing this, if the initial issue occurs again, please reopen.

**Closed by blastrock** 2018-04-28 16:06 UTC
Labels: bug

**Comment by taslimaexo-sketch** [comment] 2026-01-30 20:57
I also need help for a similar reason, my pkgj does not let me download vita games and even psp games sometimes.  What do I do? Cause I only have 1 tai in ux0.

**Comment by taslimaexo-sketch** [comment] 2026-01-30 20:59
I also need help for a similar reason, my pkgj does not let me download vita games and even psp games sometimes. What do I do? Cause I only have 1 tai in ux0.

![Image](https://github.com/user-attachments/assets/10b616b9-8783-43da-b5b8-3c999fb6a62b)
