### ISSUE TITLE
Unable to download games secPromoterUtilityPromotePkgWithRif Error

### ISSUE THREAD

**Issue by GeneralZero** [blastrock/pkgj#100] opened 2018-07-02 04:59 UTC
Version of firmware: 3.60
Version of PKGj: v0.22

## Steps to reproduce the issue
Download any PSVita game from the "show games" section

Obtained result: Error
Download failure: secPromoterUtilityPromotePkgWithRif failed:0x80870004

Expected result: Game downloaded and installed.

**Comment by GenericIceGuy** [comment] 2018-07-02 10:01
I'm not sure if it's relevant, but games that are downloaded from NPS browser also don't work with NoNpDrm, so it may not be a pkgj issue.

**Comment by blastrock** [comment] 2018-07-02 17:30
That's a problem with your NoNpDrm installation, duplicate of #74

**Closed** 2018-07-02 17:30 UTC
Labels: duplicate

**Comment by blastrock** [comment] 2018-07-02 17:39
see also #97

**Comment by GeneralZero** [comment] 2018-07-03 00:55
Here is my config and file listing. I just wiped my sd2vita card and redid everything and I cant see the issue. ux0 does not have a tai folder.

ur0:tai/config.txt
```
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/nonpdrm.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
```

files in ur0:tai
```
boot_config.txt
config.txt
gamesd.skprx
henkaku.skprx
henkaku.suprx
henkaku_config.bin
nonpdrm.skprx
taihen.skprx
version.txt
```
