### ISSUE TITLE
Can't install updates

### ISSUE THREAD

**Issue by mmmax4** [blastrock/pkgj#142] opened 2018-07-11 22:31 UTC
Version of firmware: 3.68
Version of PKGj: 0.28

## Steps to reproduce the issue

- Download an update of an installed game (blue point seen before the name of the game)
- The process ends like install a normal game

**Obtained result:** No update is install correctly on the PS TV (with an usb drive, the same with the Sony Memory Card) and the blue point is still there. On the informations of the game the version is still 1.00.

**Expected result:** The update is installed, the blue point is gone and there is a white one instead. On the informations of the game the version is superior of v1.00

**Comment by ferro212** [comment] 2018-07-11 22:38
I have the same Issue, i´ve tried the pkgj version 0.22 & 0.28 and  the issue still there, the updates don´t get installed

**Comment by TheRadziu** [comment] 2018-07-11 23:32
check your `ux0:/patch/GAMEID/` update should be there. As described many times, update is installed and game uses this update, but vita is not aware of that because app.db isnt updated with app_ver from update.

**Comment by ferro212** [comment] 2018-07-11 23:36
So, what can I do?

**Comment by mmmax4** [comment] 2018-07-11 23:58
I don't understand how to make the update recognize from the os, it still tell me to update the game.
Can this bug be fixed soon?

**Comment by blastrock** [comment] 2018-07-12 19:11
duplicate of https://github.com/blastrock/pkgj/issues/14

Even if the vita says the game is not up to date, the update is actually installed and works.

I don't know when I will get to fix this issue.

**Closed by blastrock** 2018-07-12 19:11 UTC

**Comment by ferro212** [comment] 2018-07-12 19:30
So then, the os doesn't show that the game is already updated but, the update works?

**Comment by blastrock** [comment] 2018-07-12 19:54
yes
