### ISSUE TITLE
Download failure : pkg is not supported, files are in wrong order, expected: 390000, actual: 389696

### ISSUE THREAD

**Issue by kevint0816** [blastrock/pkgj#287] opened 2019-03-12 08:20 UTC
Version of firmware: 3.65
Version of PKGj: v0.50

## Steps to reproduce the issue

- Updated from v0.49 to v0.50
- Tried downloading psp games (patapon)
- The error above appeared

Obtained result: The error described above
Expected result: Expected to download the game

I can download ps1 and ps vita games just fine, the error occurs only when downloading psp games. A few days ago I downloaded a PSP game in ISO format and copy it into the psp game folder (pspemu/ISO/) since the game I wanted to play wasn't in the pkgj. Perhaps this is the cause of the error? (this was before I updated pkgj to v0.50)

**Comment by blastrock** [comment] 2019-03-12 20:30
Please give the title id of the package that doesn't work

**Comment by buzzlambchops** [comment] 2019-03-12 22:06
I'm having the same problem with multiple downloads , PSP only. The ones I have tried:

ULUS10192
ULES00556

Downgraded to V0.49, games are now downloading.

**Comment by animekai** [comment] 2019-03-13 02:28
i think we are having the same problem, because i post the same issue, can we try installinf version 0.49 and see if is only the 0.50 version the problem?

As i said, i had tested at least 20 psp games and pc engine from top to bottom, and none works, must assume are all psp and pc engine games.

**Comment by buzzlambchops** [comment] 2019-03-13 05:05
I reverted to 0.49 and was able to download packages. In case it's specific to my settings - - - 3.65 Enso, sd2vita on ux:0, slim

**Comment by animekai** [comment] 2019-03-13 05:07
Yeah i swiched back to 0.49 too, until bugs had fixed

**Comment by Ziusun** [comment] 2019-03-13 12:22
Agreed, v0.50 seems to have issues with PSP games. From what I tried games above 100mb cause don't extract.

**Comment by dicelander** [comment] 2019-03-13 12:53
Are you guys downloading as pbp or as iso?

**Comment by Ziusun** [comment] 2019-03-13 13:03
@dicelander I dl as pbp.

**Comment by animekai** [comment] 2019-03-13 13:16
i had downloaded them as isos as forever

**Comment by blastrock** [comment] 2019-03-13 18:31
Oh so that's why I couldn't reproduce the issue, it only occurs with ISOs. Thanks!

**Comment by blastrock** [comment] 2019-03-13 18:34
Fixed in 0.51.

@Ziusun if you still have this error message, please reopen the bug. Also, include the title id of the packages you failed to download.

**Closed by blastrock** 2019-03-13 18:34 UTC
