### ISSUE TITLE
Download failure (HttpError). Error Code: 0x8041013d (FIGURED IT OUT, NETWORK ERROR)

### ISSUE THREAD

**Issue by AdamWGit** [blastrock/pkgj#251] opened 2018-12-28 20:59 UTC
Version of firmware: [3.68]
Version of PKGj: [0.43]

## Steps to reproduce the issue: None (I don't know)

- [It just randomly stopped working. At first, I couldn't open any of my downloaded game from PKGj store and then, it said it can't refresh list. Then, I updated the config.txt in VitaShell at ux0:pkgi/config.txt and added a new url, though I don't remember which one any more, url_dlcs http://nopaystation.com/tsv/PSV_DLCS.tsv I think, and the refresh worked again, but then I got the following error: Download failure: HttpError: sceHttpSendRequest failed: 0x8041013d. Played with the Tai configs and then I got NONPDRM error I think and then again got the 0x8041013d error even when I updated my plugins with AutoPlugin. Sigh, PKGj and my downloaded games started not to work when the new version was released :/ According to https://playstationdev.wiki/psvitadevwiki/index.php?title=Error_Codes , this error means this: SCE_NET_ERROR_ECONNREFUSED | 0x8041013d | NW-2465-7 | An error occurred.]

Obtained result: [Download failure: HttpError: sceHttpSendRequest failed: 0x8041013d]
Expected result: [Download X game]

[Idem.]

Edit: I just saw the links that should go in the config.txt, but even with these links, I still get the same error.

Edit 2: I FIGURED IT OUT! I PUT A CUSTOM DNS AND NOW I CAN DOWNLOAD GAMES WITHOUT ANY PROBLEMS. IT WAS A NETWORK PROBLEM.

*Leaving this issue here, since someone could have the same problem as me.*

**Comment by blastrock** [comment] 2019-01-05 10:42
Glad you figured it out. Seems like a duplicate of #245

**Closed by blastrock** 2019-01-05 10:42 UTC

**Comment by Yugo331** [comment] 2024-08-27 01:34
Gracias tuve el mismo problema y si le puse un DNS personalizado por hacer caso a un youtuber jaja gracias
