### ISSUE TITLE
Updates installed via PSN don't seem to register as installed by PKGj

### ISSUE THREAD

**Issue by edale2** [blastrock/pkgj#20] opened 2018-03-29 01:29 UTC
I've updated my nonpdrm Vita games via PSN thanks to Enso 3.65's PSN spoofing, so I'm reasonably sure they're the most recent updates; but when I look at the updates section of PKGj, instead of the white circle shown with all my other installed content, there's a purple circle. And if I hit 'X', instead of getting a message that the content is already installed, it starts to download a new update.

**Comment by blastrock** [comment] 2018-03-31 10:05
The circle never gets white on updates, this feature is harder to implement than the other because I can't just check if an update is installed, I must also check which version of the update is installed.

Duplicate of #14

**Closed by blastrock** 2018-03-31 10:05 UTC
