### ISSUE TITLE
Do not show DLC/patches for not installed games

### ISSUE THREAD

**Issue by DasTestament** [blastrock/pkgj#133] opened 2018-07-09 07:29 UTC
There is no sense in showing me the whole list of DLC\patches for games which are not installed, but scrolling this list is a pain in the ass. There should an option to "Hide that shit" or this should be done by default without any options. Latter is preferable.

**Comment by blastrock** [comment] 2018-07-09 18:06
duplicate of #40

**Closed by blastrock** 2018-07-09 18:06 UTC
