### ISSUE TITLE
Bookmarks/favorites

### ISSUE THREAD

**Issue by MNKqwerty** [blastrock/pkgj#140] opened 2018-07-11 11:19 UTC
Hi!
Is it possible to add something like list of marked games? For example, if I have not enough storage, I can bookmark the game/dlc/etc. and download it later.

**Comment by eze92** [comment] 2018-07-11 17:47
Hi, 
One question of possible enhancement , in update futures You can implements pictures the games? how the free shop of 3DS . Thanks

**Comment by blastrock** [comment] 2018-07-11 18:22
Yes, duplicate of #7 

And I don't plan to implement game pictures anytime soon as I don't have the time.

**Closed by blastrock** 2018-07-11 18:22 UTC
