### ISSUE TITLE
Application Softlock after some downloads

### ISSUE THREAD

**Issue by Scrxtchy** [blastrock/pkgj#36] opened 2018-04-05 13:06 UTC
Version of firmware: 3.65
Version of PKGj: v0.11

## Steps to reproduce the issue

 - Refresh to DLC
 - Download multipel DLC items
 - Eventually some packages fail to download (icon returns to blue circle)
 - Refresh DLC List

Obtained result: An error messeage claiming a failure to download the list
Expected result: A working function to refresh the download page

This is similar to a comment provided in #32 regarding some functions not working after a few downloads

**Comment by blastrock** [comment] 2018-04-05 18:08
Thanks for the report.

This is a duplicate of #27 . If refreshing the menu fails for whatever reason, your only choice is to restart pkgj. It seems a bit hard to fix the logic there, so this bug will stay there some time, sorry.

**Closed by blastrock** 2018-04-05 18:08 UTC
