### ISSUE TITLE
Pkgj, help please

### ISSUE THREAD

**Issue by des42** [blastrock/pkgj#319] opened 2019-12-25 17:53 UTC
PKGj does not update the list of games, gives out a connection error "can't get list: HttpError: sceHttpSendRequest failed: 0x8041013d", although I'm connected to Wi-Fi, how to fix this error?

**Comment by TheRadziu** [comment] 2019-12-26 12:13
duplicate of #312

**Closed by TheRadziu** 2019-12-26 12:13 UTC
