### ISSUE TITLE
HTTP download error 0x80431068

### ISSUE THREAD

**Issue by kohn42** [blastrock/pkgj#64] opened 2018-05-01 00:40 UTC
Version of firmware: 3.6.0
Version of PKGj: [insert version] 0.15

## Steps to reproduce the issue

Attempted to download any game of the list in PKGj, all leads to:

ERROR

Download failure: HttpError: HTTP download error 0x80431068

**Comment by TheRadziu** [comment] 2018-05-01 00:43
remove s from all https links in your config.

**Comment by kohn42** [comment] 2018-05-01 01:01
already done that

**Comment by Kojikun1** [comment] 2018-05-01 06:15
i have the same error during download and when i cancel the download

**Comment by blastrock** [comment] 2018-05-01 09:51
As you can see here: https://vitadevwiki.com/vita/Error_Codes , this error corresponds to: SCE_HTTP_ERROR_TIMEOUT. So I don't think this has to do with pkgj.

**Comment by barbabarros** [comment] 2018-05-11 21:15
sorry about my english. I have this problem too, but i think this problem does not corresponds to pkgj... i think this error is the psvita standby mode... vita turns off the wifi so pkgj show http error download... 
If you keep vita alive (ex: touching the screen), or change vita settings for 30min stand by, the game is downloaded successfully, because vita does not shutdown wifi... again, sorry about my english...

**Comment by blastrock** [comment] 2018-05-12 08:26
You might be right @barbabarros, I couldn't make pkgj support the vita going to sleep, but I didn't check what error it gives, so it may be what happens here. In my case, I changed the stand-by delay to 30min in the settings, as you said, to avoid this. Anyway, thank you for your insight.

**Comment by Hrozhek** [comment] 2018-05-19 20:16
Haha. Have the same issue. This program unable to see https://nops.youknowwhat.stuff only http. but http downloads are not available. It downloaded but then i got an error: "Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004". It is a defeinetly bug of the pkgj program

**Comment by blastrock** [comment] 2018-05-19 23:35
That's a different issue: #74

**Comment by mimshipio** [comment] 2018-06-20 20:57
I've been receiving this error too and it's definitely NOT due to the Vita going into sleep mode. I've checked this at least 5 times making sure it didn't go into sleep mode but it always returns this error. The strange thing is that it only occurs with larger files. i was able to download smaller games (~1GB) no problem, but if I try to download a larger game (>2GB) it stops downloading the file about halfway through and then when I cancel the dowload it returns this error.

**Comment by kenshin088** [comment] 2018-06-21 20:41
Having this issue too. Haven't been able to download a game in over a month. Any solution?

**Comment by blastrock** [comment] 2018-07-11 19:10
duplicate of #104 and #141, sorry guys I just can't reproduce these...

**Closed by blastrock** 2018-07-11 19:10 UTC

**Comment by gendolookin** [comment] 2021-04-30 11:48
Not sure this is everyone’s problem. I just recently copied my sd2vita to a new sd card. Then I got this problem. After turning off the WiFi Power saving mode in the Power settings it solved my issue.
