### ISSUE TITLE
Version is still 1.00 even after updated

### ISSUE THREAD

**Issue by xswqaz** [blastrock/pkgj#67] opened 2018-05-06 01:49 UTC
Version of firmware: 3.65
Version of PKGj: 0.16

## Steps to reproduce the issue

Obtained result:
Even though updated, version is 1.00
(Checked it from information tab from Icon)
Everytime launched it, system urge it update

What means blue circle of update list?
There is no change update before after

Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment] 2018-05-06 11:33
I guess you are talking about a game update. The game is updated, even if the version shows 1.00, check the version in game, not in the menu.

Duplicate of #14

**Closed by blastrock** 2018-05-06 11:33 UTC
