### ISSUE TITLE
Unable to compile pkgj

### ISSUE THREAD

**Issue by baregl** [blastrock/pkgj#167] opened 2018-07-28 08:46 UTC
Version of firmware: -
Version of PKGj: 876612815

## Steps to reproduce the issue

- Clone git Repo
- Execute ```cmake .```

Obtained result: cmake complains about a missing conanbuildinfo.cmake file  and fails at ```conan_basic_setup```
Expected result: Built pkgj

Installing conan and the executing ```conan install .``` according to the [docs](https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html) fails with:
```
ERROR: PROJECT: Error in requirements() method, line 9
	if self.settings.os == "PSVita":
	ConanException: Invalid setting 'PSVita' is not a valid 'settings.os' value.
Possible values are ['Android', 'Arduino', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

I'm unable to find a vita specific conan fork

**Comment by blastrock** [comment] 2018-07-29 08:14
duplicate of #166. In the meantime, you can see how ci.sh builds pkgj. Your problem is related to ~/.conan/settings.yml .

**Closed by blastrock** 2018-07-29 08:14 UTC
