### ISSUE TITLE
Feature Request: "Wish List"

### ISSUE THREAD

**Issue by Saix13** [blastrock/pkgj#358] opened 2020-05-23 13:24 UTC
I sometimes forget what games I was thinking about installing once I finish games already installed and I clear out space for new games. Being able to mark games as such and then a filter option to show just them would be useful for a good number of users I would think.

**Comment by TheRadziu** [comment] 2020-05-23 14:03
dupe of #7

**Closed by TheRadziu** 2020-05-23 14:03 UTC
