### ISSUE TITLE
Cant download psx games

### ISSUE THREAD

**Issue by CurleyFrie** [blastrock/pkgj#415] opened 2023-07-29 23:08 UTC
Hardware: PSV
Version of firmware: 3.65
Version of PKGj: 0.56

1 Step to reproduce the issue

- Download any game off the psx list
- 
- 

Obtained result: At the end of the download it says "Download failure: failed to rename: 0x80010016"
Expected result: The game downloads with no issue

I can download psp and vita games but psx game dont work at all. Before this issue I qued up about 4 or 5 psx games and then came back to my vita with the same error on each download

**Comment by LiEnby** [comment] 2023-07-30 00:04
duplicate of #414

**Closed by LiEnby** 2023-07-30 00:04 UTC
