### ISSUE TITLE
please, Is it possible to adding options for manual save location file for psx game?

### ISSUE THREAD

**Issue by xPSV** [blastrock/pkgj#51] opened 2018-04-21 12:07 UTC
Version of firmware: [3.60, 3.65]
Version of PKGj: [0.13]

This is request for enhancement
1. List and Menu for loading PSP Game.
2. Options for manual save location file for PSX/PSP games.

I used old vita memory to (uma0:) and sd2vita(ux0:)
- my ux0: Only storage VITA Game / DLC
- my uma0: Only Storage game files for Adrenaline (PSP/PSX/Rom emulator etc.)

but PKGJ can only save and unpack to main memory at ux0:
so Adrenaline can't locate to game file at ux0: (if we setting it navigate to  uma0:pspemu/)
and my solution is copy and paste it into right location by vitashell then delete it.

please, Is it possible to enhancement this request?

and also Thanks for your hard work.

**Comment by blastrock** [comment] 2018-04-21 14:35
Yup, it's on the to-do list.

Duplicate of #6

**Closed by blastrock** 2018-04-21 14:35 UTC

**Comment by xPSV** [comment] 2018-04-21 14:36
Oh! that sound great. thank you very much.
