### ISSUE TITLE
Can't get list [...] 0x80410136

### ISSUE THREAD

**Issue by Zarvera** [blastrock/pkgj#316] opened 2019-12-17 16:19 UTC
Version of PKGj: 0:52

## Steps to reproduce the issue

-Refresh the list in the PKGj

Obtained result: The 0x80410136 error
Expected result: List of apps

I did read the FAQ, installed itl-enso as advised and tried all the manipulations it provides. Tried deleting pkgj folder from ux0, tried reinstalling PKGj off of github .vpk, tried asking it nicely etc., still can't get the list

**Comment by TheRadziu** [comment] 2019-12-24 13:41
duplicate of #312 
Please refer to my answer and further support in there.

**Closed by TheRadziu** 2019-12-24 13:41 UTC

**Comment by Zarvera** [comment] 2019-12-24 14:01
> as for now russian citizens can't access it due to server range being blocked (some anti-homo law, idk)
Aight, that explains it candidly. thanks mr poutine
