### ISSUE TITLE
PSP games don't install correctly

### ISSUE THREAD

**Issue by xPSV** [blastrock/pkgj#61] opened 2018-04-30 06:49 UTC
Version of firmware: [3.65enso / 3.60enso / 3.60taiHen]
Version of PKGj: [0.14 / 0.15]

I tested all three of my devices.
- Adrenaline663 installed.
- Last plugin nonpdrm.skprx installed.
- and try to reboot all vita.

Only psp game don't install correctly like (ux0:pspemu/PSP/GAME/....) 
but they will be at (ux0:pkgi/) folder instead.

This problem does not happen with psx games.

Thanks for your reply and respect your great work.

**Comment by xPSV** [comment] 2018-04-30 07:01
Oh I just create ISO folder in ux0:pspemu
It will automatically convert to ISO file.

thanks

**Comment by blastrock** [comment] 2018-04-30 21:30
Duplicate of #58

**Closed by blastrock** 2018-04-30 21:30 UTC
