### ISSUE TITLE
Add filter to show DLCs for installed apps

### ISSUE THREAD

**Issue by azumukupoe** [blastrock/pkgj#119] opened 2018-07-06 06:16 UTC
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment] 2018-07-09 18:06
duplicate of #40

**Closed by blastrock** 2018-07-09 18:06 UTC
