### ISSUE TITLE
Scrolling issue while download is on

### ISSUE THREAD

**Issue by pkly** [blastrock/pkgj#201] opened 2018-09-15 07:30 UTC
Version of firmware: 3.65
Version of PKGj: 0.34 - 0.36 (still an issue)

## Steps to reproduce the issue

- Start a download
- Start scrolling down or up a long distance

Obtained result: Scrolling occurs normally and there's no framedrops or artifacts
Expected result: Scrolling can start slowing down to a crawl when you move your cursor from the downloaded item too far, artifacts will appear (triangles in the background, disappearing portions of the text, etc.)

This happened to me multiple times, I think it might happen only during dling of bigger vita games (~3gb)

**Comment by guch8017** [comment] 2018-09-16 10:58
I think this problem not only happens when a download task is running. When the list is too long, and when I move down to someplace, it starts to slow down. I think this isn’t caused by a download task.

**Comment by pkly** [comment] 2018-09-16 11:03
I only ever have this issue when a download is on.

**Comment by blastrock** [comment] 2018-09-16 12:01
I'm gonna mark this as a duplicate of #28 . When you are downloading certain packages, the whole app kind of lags. I don't really know how to fix this yet.

@guch8017 This is another issue. That's a cache filling up in pkgj. If you scroll back up and scroll down again, it will scroll down smoothly. I planned to fix that too, it should be easier fix though.

**Closed by blastrock** 2018-09-16 12:01 UTC
