### ISSUE TITLE
Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004

### ISSUE THREAD

**Issue by kayada** [blastrock/pkgj#110] opened 2018-07-04 09:51 UTC
Version of firmware: 3.68
Version of PKGj: v0.23

When i opened a game from pkgj without henkaku the game wont start so i install henkaku again but it still wont open. i tried downloading another game in pkgj but it wont install and this pop up 
Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004
it was working fine before but after i open a game without installing henkaku this happen. Btw i tried reinstalling everything but still wont work

**Comment by RY0M43CH1Z3N** [comment] 2018-07-04 11:30
Is a Nonpdrm error. Please try to reinstall the plugin in the latest versión (1.2) in the same partition as PKGj.

**Comment by blastrock** [comment] 2018-07-04 20:08
duplicate of #74, #97 etc

**Closed by blastrock** 2018-07-04 20:08 UTC
