### ISSUE TITLE
Download failure: failed to rename: 0x80010002

### ISSUE THREAD

**Issue by darkdragon241** [blastrock/pkgj#122] opened 2018-07-07 13:37 UTC
Version of firmware: 3.68
Version of PKGj: 0.23

## Steps to reproduce the issue

- Download any game's update
- Got error

Obtained result: Error: Download failure: failed to rename: 0x80010002
Expected result: Able to install updates

So I tried to download an update for a game. The download is normal but after it finishes downloading the update the error appears and say:

ERROR
Download failure: failed to rename: 0x80010002

It happens to every game, the DLC and the games download are normal, only the update got an issue

**Comment by blastrock** [comment] 2018-07-07 14:07
You must create the ux0:patch folder manually, will be fixed

duplicate of #101

**Closed by blastrock** 2018-07-07 14:07 UTC
