### ISSUE TITLE
game update not working

### ISSUE THREAD

**Issue by ronnyc4** [blastrock/pkgj#115] opened 2018-07-05 15:37 UTC
ps vita 3.68 h-encore
game borderlands 2 update not installed.
download success. its already in ux0:/patch/ folder. it just don't detect the update
and in pkgj, borderlands 2 update icon still blue circle.

**Comment by blastrock** [comment] 2018-07-06 18:43
Known bug. The patch is installed and works nonetheless.

duplicate of #14

**Closed by blastrock** 2018-07-06 18:43 UTC
